
import java.util.HashMap;

/*
389. Find the Difference

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Leetcode: https://leetcode.com/problems/find-the-difference/description/
*/
class String7_389{
    public char findTheDifference(String s, String t) {

        HashMap <Character, Integer> map=new HashMap<>();
        for (int i = 0; i < s.length(); i++) {
            char ch= s.charAt(i);
            if(map.containsKey(ch)){
                map.put(ch, map.get(ch)+1);
            }
            else{
                map.put(ch, 1);
            }
        }

        for (int i = 0; i < t.length(); i++) {
            char ch=t.charAt(i);
            if(!map.containsKey(ch)){
                return ch;
            }
            map.put(ch, map.get(ch) - 1);
            if(map.get(ch)<0){
                return ch;
            }
        }

        return ' ';
        
    }
}

/* Another Solution:
class Solution {
    public char findTheDifference(String s, String t) {
        Map<Character, Integer> count = new HashMap<>();
        
        for (char c : t.toCharArray()) {
            count.put(c, count.getOrDefault(c, 0) + 1);
        }
        
        for (char c : s.toCharArray()) {
            count.put(c, count.get(c) - 1);
            if (count.get(c) == 0) {
                count.remove(c);
            }
        }
        
        return (char) count.keySet().toArray()[0];        
    }
}
*/